"""allow anonymous input (user_id nullable + ondelete SET NULL)

Revision ID: 04be657fc5f4
Revises: 
Create Date: 2025-08-14 14:33:02.973945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04be657fc5f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('input_data', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('input_data', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
